//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer_Details
    {
        public string CUS_id { get; set; }
        public string CUS_firstname { get; set; }
        public string CUS_surname { get; set; }
        public string CUS_BirthDate { get; set; }
        public string CUS_Email { get; set; }
        public string CUS_Phone { get; set; }
        public string Address { get; set; }

        public static implicit operator Tbl_Customer_Details(Tbl_Customer_Details v)
        {
            throw new NotImplementedException();
        }
    }
}
